library(tibble)
library(dplyr)
library(arrow)
library(stringr)

commodities <- tibble(
  commodity_code = c("01","02",
                     "03","04","05","06","07","08","09","10",
                     "11","12","13","14","15","16","17",
                     "18","19","20","21","22","23","24","25",
                     "26","27","28","29","30","31","32","33",
                     "34","35","36","37","38","39","40","41",
                     "42","43","44","45","46","47","48","49",
                     "50","51","52","53","54","55","56","57",
                     "58","59","60","61","62","63","64",
                     "65","66","67","68","69","70","71","72",
                     "73","74","75","76","78","79","80","81",
                     "82","83","84","85","86","87","88","89",
                     "90","91","92","93","94","95","96","97",
                     "99","all"),
  commodity_fullname_english = c("Alias for all codes in the group Animals; live",
                                 "Alias for all codes in the group Meat and edible meat offal",
                                 "Alias for all codes in the group Fish and crustaceans, molluscs and other aquatic invertebrates",
                                 "Alias for all codes in the group Dairy produce; birds' eggs; natural honey; edible products of animal origin, not elsewhere specified or included",
                                 "Alias for all codes in the group Animal originated products; not elsewhere specified or included",
                                 "Alias for all codes in the group Trees and other plants, live; bulbs, roots and the like; cut flowers and ornamental foliage",
                                 "Alias for all codes in the group Vegetables and certain roots and tubers; edible",
                                 "Alias for all codes in the group Fruit and nuts, edible; peel of citrus fruit or melons",
                                 "Alias for all codes in the group Coffee, tea, mate and spices",
                                 "Alias for all codes in the group Cereals",
                                 "Alias for all codes in the group Products of the milling industry; malt, starches, inulin, wheat gluten",
                                 "Alias for all codes in the group Oil seeds and oleaginous fruits; miscellaneous grains, seeds and fruit, industrial or medicinal plants; straw and fodder",
                                 "Alias for all codes in the group Lac; gums, resins and other vegetable saps and extracts",
                                 "Alias for all codes in the group Vegetable plaiting materials; vegetable products not elsewhere specified or included",
                                 "Alias for all codes in the group Animal or vegetable fats and oils and their cleavage products; prepared animal fats; animal or vegetable waxes",
                                 "Alias for all codes in the group Meat, fish or crustaceans, molluscs or other aquatic invertebrates; preparations thereof",
                                 "Alias for all codes in the group Sugars and sugar confectionery",
                                 "Alias for all codes in the group Cocoa and cocoa preparations",
                                 "Alias for all codes in the group Preparations of cereals, flour, starch or milk; pastrycooks' products",
                                 "Alias for all codes in the group Preparations of vegetables, fruit, nuts or other parts of plants",
                                 "Alias for all codes in the group Miscellaneous edible preparations",
                                 "Alias for all codes in the group Beverages, spirits and vinegar",
                                 "Alias for all codes in the group Food industries, residues and wastes thereof; prepared animal fodder",
                                 "Alias for all codes in the group Tobacco and manufactured tobacco substitutes",
                                 "Alias for all codes in the group Salt; sulphur; earths, stone; plastering materials, lime and cement",
                                 "Alias for all codes in the group Ores, slag and ash",
                                 "Alias for all codes in the group Mineral fuels, mineral oils and products of their distillation; bituminous substances; mineral waxes",
                                 "Alias for all codes in the group Inorganic chemicals; organic and inorganic compounds of precious metals; of rare earth metals, of radio-active elements and of isotopes",
                                 "Alias for all codes in the group Organic chemicals",
                                 "Alias for all codes in the group Pharmaceutical products",
                                 "Alias for all codes in the group Fertilizers",
                                 "Alias for all codes in the group Tanning or dyeing extracts; tannins and their derivatives; dyes, pigments and other colouring matter; paints, varnishes; putty, other mastics; inks",
                                 "Alias for all codes in the group Essential oils and resinoids; perfumery, cosmetic or toilet preparations",
                                 "Alias for all codes in the group Soap, organic surface-active agents; washing, lubricating, polishing or scouring preparations; artificial or prepared waxes, candles and similar articles, modelling pastes, dental waxes and dental preparations with a basis of plaster",
                                 "Alias for all codes in the group Albuminoidal substances; modified starches; glues; enzymes",
                                 "Alias for all codes in the group Explosives; pyrotechnic products; matches; pyrophoric alloys; certain combustible preparations",
                                 "Alias for all codes in the group Photographic or cinematographic goods",
                                 "Alias for all codes in the group Chemical products n.e.c.",
                                 "Alias for all codes in the group Plastics and articles thereof",
                                 "Alias for all codes in the group Rubber and articles thereof",
                                 "Alias for all codes in the group Raw hides and skins (other than furskins) and leather",
                                 "Alias for all codes in the group Articles of leather; saddlery and harness; travel goods, handbags and similar containers; articles of animal gut (other than silk-worm gut)",
                                 "Alias for all codes in the group Furskins and artificial fur; manufactures thereof",
                                 "Alias for all codes in the group Wood and articles of wood; wood charcoal",
                                 "Alias for all codes in the group Cork and articles of cork",
                                 "Alias for all codes in the group Manufactures of straw, esparto or other plaiting materials; basketware and wickerwork",
                                 "Alias for all codes in the group Pulp of wood or other fibrous cellulosic material; recovered (waste and scrap) paper or paperboard",
                                 "Alias for all codes in the group Paper and paperboard; articles of paper pulp, of paper or paperboard",
                                 "Alias for all codes in the group Printed books, newspapers, pictures and other products of the printing industry; manuscripts, typescripts and plans",
                                 "Alias for all codes in the group Silk",
                                 "Alias for all codes in the group Wool, fine or coarse animal hair; horsehair yarn and woven fabric",
                                 "Alias for all codes in the group Cotton",
                                 "Alias for all codes in the group Vegetable textile fibres; paper yarn and woven fabrics of paper yarn",
                                 "Alias for all codes in the group Man-made filaments; strip and the like of man-made textile materials",
                                 "Alias for all codes in the group Man-made staple fibres",
                                 "Alias for all codes in the group Wadding, felt and nonwovens, special yarns; twine, cordage, ropes and cables and articles thereof",
                                 "Alias for all codes in the group Carpets and other textile floor coverings",
                                 "Alias for all codes in the group Fabrics; special woven fabrics, tufted textile fabrics, lace, tapestries, trimmings, embroidery",
                                 "Alias for all codes in the group Textile fabrics; impregnated, coated, covered or laminated; textile articles of a kind suitable for industrial use",
                                 "Alias for all codes in the group Fabrics; knitted or crocheted",
                                 "Alias for all codes in the group Apparel and clothing accessories; knitted or crocheted",
                                 "Alias for all codes in the group Apparel and clothing accessories; not knitted or crocheted",
                                 "Alias for all codes in the group Textiles, made up articles; sets; worn clothing and worn textile articles; rags",
                                 "Alias for all codes in the group Footwear; gaiters and the like; parts of such articles",
                                 "Alias for all codes in the group Headgear and parts thereof",
                                 "Alias for all codes in the group Umbrellas, sun umbrellas, walking-sticks, seat sticks, whips, riding crops; and parts thereof",
                                 "Alias for all codes in the group Feathers and down, prepared; and articles made of feather or of down; artificial flowers; articles of human hair",
                                 "Alias for all codes in the group Stone, plaster, cement, asbestos, mica or similar materials; articles thereof",
                                 "Alias for all codes in the group Ceramic products",
                                 "Alias for all codes in the group Glass and glassware",
                                 "Alias for all codes in the group Natural, cultured pearls; precious, semi-precious stones; precious metals, metals clad with precious metal, and articles thereof; imitation jewellery; coin",
                                 "Alias for all codes in the group Iron and steel",
                                 "Alias for all codes in the group Iron or steel articles",
                                 "Alias for all codes in the group Copper and articles thereof",
                                 "Alias for all codes in the group Nickel and articles thereof",
                                 "Alias for all codes in the group Aluminium and articles thereof",
                                 "Alias for all codes in the group Lead and articles thereof",
                                 "Alias for all codes in the group Zinc and articles thereof",
                                 "Alias for all codes in the group Tin; articles thereof",
                                 "Alias for all codes in the group Metals; n.e.c., cermets and articles thereof",
                                 "Alias for all codes in the group Tools, implements, cutlery, spoons and forks, of base metal; parts thereof, of base metal",
                                 "Alias for all codes in the group Metal; miscellaneous products of base metal",
                                 "Alias for all codes in the group Nuclear reactors, boilers, machinery and mechanical appliances; parts thereof",
                                 "Alias for all codes in the group Electrical machinery and equipment and parts thereof; sound recorders and reproducers; television image and sound recorders and reproducers, parts and accessories of such articles",
                                 "Alias for all codes in the group Railway, tramway locomotives, rolling-stock and parts thereof; railway or tramway track fixtures and fittings and parts thereof; mechanical (including electro-mechanical) traffic signalling equipment of all kinds",
                                 "Alias for all codes in the group Vehicles; other than railway or tramway rolling stock, and parts and accessories thereof",
                                 "Alias for all codes in the group Aircraft, spacecraft and parts thereof",
                                 "Alias for all codes in the group Ships, boats and floating structures",
                                 "Alias for all codes in the group Optical, photographic, cinematographic, measuring, checking, medical or surgical instruments and apparatus; parts and accessories",
                                 "Alias for all codes in the group Clocks and watches and parts thereof",
                                 "Alias for all codes in the group Musical instruments; parts and accessories of such articles",
                                 "Alias for all codes in the group Arms and ammunition; parts and accessories thereof",
                                 "Alias for all codes in the group Furniture; bedding, mattresses, mattress supports, cushions and similar stuffed furnishings; lamps and lighting fittings, n.e.c.; illuminated signs, illuminated name-plates and the like; prefabricated buildings",
                                 "Alias for all codes in the group Toys, games and sports requisites; parts and accessories thereof",
                                 "Alias for all codes in the group Miscellaneous manufactured articles",
                                 "Alias for all codes in the group Works of art; collectors' pieces and antiques",
                                 "Alias for all codes in the group Commodities not specified according to kind",
                                 "Alias for all codes")
)

countries <- tibble(
  country_iso = c("c-af", "c-am", "c-as", "c-eu", "c-oc", "all"),
  country_name_english = c("Alias for all valid ISO codes in Africa",
                           "Alias for all valid ISO codes in the Americas",
                           "Alias for all valid ISO codes in Asia","Alias for all valid ISO codes in Europe",
                           "Alias for all valid ISO codes in Oceania",
                           "Alias for all valid ISO codes in the World"),
  continent_id = c(1:5, NA),
  continent_name_english = c("Africa", "Americas", "Asia", "Europe", "Oceania", NA)
)

countries2 <- tibble(
  country_iso = c("ata", "bes", "blm", "cuw", "sxm", "ssd"),
  country_name_english = c("Antarctica", "Bonaire, Sint Eustatius and Saba", 
                           "Saint Barthelemy", "Curacao", "Sint Maarten", "South Sudan"),
  country_fullname_english = c("Antarctica", "Bonaire, Sint Eustatius and Saba", 
                               "Saint Barthelemy", "Curacao", "Sint Maarten", "South Sudan"),
  continent_id = c(6, 5, 5, 5, 5, 3),
  continent_name_english = c("Antarctica", "Americas", "Americas", "Americas", "Americas", "Africa"),
  eu28_member = c(0, 0, 0, 0, 0, 0)
)

areas <- tibble(
  country_iso = c("e-80","e-129","e-221","e-290","e-471","e-472","e-473",
                  "e-490","e-492","e-527","e-536","e-568","e-577","e-636",
                  "e-637","e-697","e-837","e-838","e-839","e-849","e-879",
                  "e-899"),
  country_name_english = c("British Antarctic Territory",
                           "Caribbean, not elsewhere specified",
                           "Eastern Europe, not elsewhere specified",
                           "Northern Africa, not elsewhere specified",
                           "Central American Common Market, not elsewhere specified",
                           "Central African Monetary and Economic Union, not elsewhere specified",
                           "Latin American Integration Association, not elsewhere specified",
                           "Other Asia, not elsewhere specified",
                           "European Union, not elsewhere specified",
                           "Oceania, not elsewhere specified",
                           "Neutral zone",
                           "Other Europe, not elsewhere specified",
                           "Other Africa, not elsewhere specified",
                           "Rest of America, not elsewhere specified",
                           "North America and Central America, not elsewhere specified",
                           "Europe EFTA, not elsewhere specified",
                           "Bunkers",
                           "Free zones",
                           "Special categories",
                           "United States Miscellaneous Pacific Islands",
                           "Western Asia, not elsewhere specified",
                           "Areas, not elsewhere specified"),
  continent_id = case_when(
    str_match(country_name_english, "Antarctic") == "Antarctic" ~ 6,
    str_match(country_name_english, "Caribbean") == "Caribbean" ~ 2,
    str_match(country_name_english, "America") == "America" ~ 2,
    str_match(country_name_english, "Pacific") == "Pacific" ~ 2,
    str_match(country_name_english, "Europe") == "Europe" ~ 4,
    str_match(country_name_english, "Africa") == "Africa" ~ 1,
    str_match(country_name_english, "Asia") == "Asia" ~ 3,
    str_match(country_name_english, "Oceania") == "Oceania" ~ 5
  ),
  continent_name_english = case_when(
    str_match(country_name_english, "Antarctic") == "Antarctic" ~ "Antarctica",
    str_match(country_name_english, "Caribbean") == "Caribbean" ~ "Americas",
    str_match(country_name_english, "America") == "America" ~ "Americas",
    str_match(country_name_english, "Pacific") == "Pacific" ~ "Americas",
    str_match(country_name_english, "Europe") == "Europe" ~ "Europe",
    str_match(country_name_english, "Africa") == "Africa" ~ "Africa",
    str_match(country_name_english, "Asia") == "Asia" ~ "Asia",
    str_match(country_name_english, "Oceania") == "Oceania" ~ "Oceania"
  )
)

write_parquet(commodities, "aliases/commodities.parquet")

write_parquet(
  bind_rows(
    countries,
    countries2,
    areas
  ) %>% 
    arrange(country_iso),
  "aliases/countries.parquet"
)
